version: '3'

services:
  nginx-web:
    image: pixelfordinner/nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: app-pixelcloud-nginx_proxy-nginx
    restart: unless-stopped
    ports:
      - '${HTTP_PORT}'
      - '${HTTPS_PORT}'
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./volumes/nginx/html:/usr/share/nginx/html:ro
    networks:
      - proxy-tier
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup app-pixelcloud-nginx_proxy-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: app-pixelcloud-nginx_proxy-nginx_gen
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/certs:/etc/nginx/certs:ro
      - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/docker-gen/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - proxy-tier
    logging:
      options:
        max-size: '4m'
        max-file: '10'

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: app-pixelcloud-nginx_proxy-letsencrypt
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/conf.d:/etc/nginx/conf.d
      - ./volumes/nginx/vhost.d:/etc/nginx/vhost.d
      - ./volumes/nginx/html:/usr/share/nginx/html
      - ./volumes/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: app-pixelcloud-nginx_proxy-nginx_gen
      NGINX_PROXY_CONTAINER: app-pixelcloud-nginx_proxy-nginx
      ACME_CA_URI: ${ACME_CA_URI}
    networks:
      - proxy-tier
    logging:
      options:
        max-size: '4m'
        max-file: '10'

networks:
  proxy-tier:
    external:
      name: nginx-proxy
